import { Box, Container, Heading, Text, Accordion, AccordionItem, AccordionButton, AccordionPanel, AccordionIcon } from "@chakra-ui/react";

const faqs = [
  {
    question: "What is an AI product photo?",
    answer: "An AI product photo is a product image generated or enhanced using artificial intelligence instead of traditional photography. With tools like Topview, sellers and marketers can create realistic AI product photos, adjust backgrounds, lighting, and scenes, and produce commercial-ready visuals without a physical photoshoot."
  },
  {
    question: "How does AI product photography work?",
    answer: "AI product photography uses advanced image generation models to transform a single product image into multiple high-quality visuals. Topview combines leading AI models with an intuitive workflow, allowing users to generate studio, lifestyle, and marketing-focused AI product images in just a few clicks."
  },
  {
    question: "Can AI product photos be used for e-commerce and ads?",
    answer: "Yes. Professional AI product photos are designed for commercial use and are widely used for Amazon listings, Shopify stores, and paid advertising. Topview generates AI product photography that meets the visual requirements of major e-commerce platforms and social media ad formats."
  },
  {
    question: "Do I need design or photography skills to use AI product photo tools?",
    answer: "No. AI product photo generators are built for non-designers. With Topview, users can create and edit AI product images through a simple interface, without Photoshop skills or photography experience."
  },
  {
    question: "Can I create multiple product images from one photo?",
    answer: "Yes. One of the main benefits of product photography AI is scalability. Using Topview, a single product image can be transformed into multiple AI product photos with different backgrounds, styles, and compositions, ideal for A/B testing and multi-platform marketing."
  },
  {
    question: "What is an AI Product Avatar and how is it used?",
    answer: "An AI Product Avatar is a digital model generated by AI that can hold and showcase products in realistic scenarios. With Topview, businesses can combine AI product photos with AI-generated models to create engaging product ads, lifestyle visuals, and promotional images without hiring real models."
  },
  {
    question: "How is AI product photography different from traditional product photography?",
    answer: "Traditional product photography requires studios, equipment, photographers, and models. AI product photography eliminates these steps by generating high-quality AI product images digitally, reducing cost, production time, and creative limitations while enabling rapid iteration."
  },
  {
    question: "Is AI product photography suitable for small businesses and DTC brands?",
    answer: "Yes. AI product photography is especially valuable for small businesses, DTC brands, and cross-border sellers who need professional visuals without high production costs. Topview helps teams scale AI product photos quickly while maintaining consistent quality."
  }
];

const FAQSection = () => {
  return (
    <Box as="section" py={{ base: 12, md: 24 }} px="6" bg="black" position="relative" overflow="hidden">
      <Container maxW="container.md">
        <Heading
          as="h2"
          size={{ base: "2xl", md: "4xl" }}
          textAlign="center"
          mb={12}
          color="white"
          fontWeight="black"
          lineHeight="1.1"
        >
          <Text as="span" bgGradient="linear(to-r, #FF6B6B, brand.500, #4ECDC4)" bgClip="text">
            AI Product Photo
          </Text> FAQ
        </Heading>

        <Accordion allowToggle>
          {faqs.map((faq, index) => (
            <AccordionItem
              key={index}
              border="1px solid"
              borderColor="whiteAlpha.200"
              borderRadius="2xl"
              bg="whiteAlpha.50"
              mb="4"
              overflow="hidden"
            >
              <h3>
                <AccordionButton py="6" _hover={{ bg: "whiteAlpha.100" }}>
                  <Box flex="1" textAlign="left" fontWeight="medium" color="white">
                    {faq.question}
                  </Box>
                  <AccordionIcon color="gray.400" />
                </AccordionButton>
              </h3>
              <AccordionPanel pb="6" color="gray.400">
                {faq.answer}
              </AccordionPanel>
            </AccordionItem>
          ))}
        </Accordion>
      </Container>
    </Box>
  );
};

export default FAQSection;
