import { Box, Container, Heading, Text, Accordion, AccordionItem, AccordionButton, AccordionPanel, AccordionIcon } from "@chakra-ui/react";

const faqs = [
  {
    question: "What specific AI models do you use for text to video?",
    answer: "We integrate the best models including OpenAI's GPT-4o for scripting and Sora/Veo/Nano Banana for visual generation.",
  },
  {
    question: "Can I turn a long article into a video?",
    answer: "Yes, our Agent can summarize long articles and blog posts into concise video scripts for social media.",
  },
  {
    question: "Do I own the copyright to the generated video?",
    answer: "Yes, all videos generated by Topview are cleared for commercial use on platforms like TikTok, YouTube, and Meta Ads.",
  },
  {
    question: "Can the AI generate voiceovers from my text?",
    answer: "Absolutely. We offer 100+ ultra-realistic AI voices in multiple languages to read your script.",
  },
  {
    question: "Can I use Topview for TikTok and Instagram Ads?",
    answer: "Yes, Topview is specifically optimized for social media. It produces high-converting 9:16 vertical videos with native-style captions, hooks, and pacing that are proven to perform on TikTok, Reels, and Shorts.",
  },
  {
    question: "Do I need professional editing skills?",
    answer: "Not at all. Topview is designed for everyone. Our AI Agent handles all the complex editing, scripting, and visual composition. If you can paste a link or type a description, you can create a professional video.",
  },
];

const FAQSection = () => {
  return (
    <Box as="section" py="20" px="6">
      <Container maxW="container.md">
        <Heading as="h2" textAlign="center" size={{ base: "2xl", md: "4xl" }} fontWeight="black" mb="12" color="white">
          <Text as="span" bgGradient="linear(to-r, #FF6B6B, #805AD5, #4ECDC4)" bgClip="text">
            Text to Video
          </Text>{" "}
          FAQ
        </Heading>

        <Accordion allowToggle>
          {faqs.map((faq, index) => (
            <AccordionItem
              key={index}
              border="1px solid"
              borderColor="whiteAlpha.200"
              borderRadius="2xl"
              bg="whiteAlpha.50"
              mb="4"
              overflow="hidden"
            >
              <Heading as="h3">
                <AccordionButton py="6" _hover={{ bg: "whiteAlpha.100" }}>
                  <Box flex="1" textAlign="left" fontWeight="medium" color="white" fontSize="md">
                    {faq.question}
                  </Box>
                  <AccordionIcon color="gray.400" />
                </AccordionButton>
              </Heading>
              <AccordionPanel pb="6" color="gray.400">
                {faq.answer}
              </AccordionPanel>
            </AccordionItem>
          ))}
        </Accordion>
      </Container>
    </Box>
  );
};

export default FAQSection;
